### ISSUE TITLE
OptionError: "No such keys(s): 'compute.use_numexpr'"

### ISSUE THREAD

**Issue by hemzyt** [judopro/Stock_Support_Resistance_ML#1]
![image](https://user-images.githubusercontent.com/59553279/79146772-bd603300-7d77-11ea-8c2b-e9b7d7e92138.png)

**Comment by judopro** [comment]
It could be due to an older version of pandas in your system. Can you check ? I am running pandas 0.24.2, and pandas-datareader 0.7.0. That method it complains about ‘compute.use_numexpr’ may not be available in an older version of pandas.
